#ifndef __PROTOCOLS_H__
#define __PROTOCOLS_H__

#define PT "protocol"

enum PROTOCOLS
{
	REQUEST_GAME_START = 10000,
	REQUEST_CARD_PICK,
	REQUEST_CLEAR_SCREEN,
	REQUEST_REFRASH,

	RESPOND_CARD_LIST = 20000,
	RESPOND_GAME_START,
	RESPOND_TURN_CHANGE,
	RESPOND_GAMEOVER,


	RESPOND_CLEAR_SCREEN,

	RESPOND_TEMP,

	RESPOND_ERR
};

#endif // !__PROTOCOLS_H__
